name: wavepower_usecase
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pymt=1.3.1
  - numpy=1.23.5
  - xarray
  - matplotlib=3.6.2
  - jupyter
  - bmi-wavewatch3
  - pip
  - pip:
    - windrose
    - git+https://github.com/pymt-lab/pymt_wavewatch3.git
 

